# Generated by Django 4.0.4 on 2022-05-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futmax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futupload',
            name='method',
            field=models.CharField(choices=[('cash', 'cash'), ('credit card', 'credit card'), ('crypto', 'crypto')], default='credit card', max_length=11),
        ),
    ]
