# Generated by Django 4.0.4 on 2022-05-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futmax', '0002_futupload_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futupload',
            name='scripts',
        ),
    ]
