# Generated by Django 4.0.4 on 2022-05-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futmax', '0003_remove_futupload_scripts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='futupload',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('FutCrypt', 'FutCrypt')], default='Cash', max_length=11),
        ),
        migrations.AlterField(
            model_name='futupload',
            name='price',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('INTERMEDIATE', 'INTERMEDIATE'), ('STARTUP', 'STARTUP'), ('SUPREME', 'SUPREME')], default='BASIC', max_length=12),
        ),
    ]
